<a href="https://colab.research.google.com/github/nahid4125/AI-lab/blob/main/lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#1d array
ary = np.array([45, 15, 78, 13])
print(ary)

#2d array
ary = np.array([[18, 24, 48], [34, 48, 47]])
print(ary)

#3D array
ary = np.array([[[10, 20, 30], [45, 55, 65]], [[48, 44, 55], [20, 40, 60]]])
print(ary)

#dimention
ar1 = np.array(100)
ar2 = np.array([44,78,95])
ar3 = np.array([[1, 2, 3], [4, 5, 6]])
ar4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(ar1.ndim)
print(ar2.ndim)
print(ar3.ndim)
print(ar4.ndim)

[45 15 78 13]
[[18 24 48]
 [34 48 47]]
[[[10 20 30]
  [45 55 65]]

 [[48 44 55]
  [20 40 60]]]
0
1
2
3


In [3]:
#indexing
ar = np.array([1, 2, 3, 4])

print(ar[2] + ar[3])

ar = np.array([[10,20,30,40,50], [60,70,80,90,100]])
print('3rd element of 1st row: ', ar[0, 2])

ar = np.array([[11,22,33,44,55], [66,77,88,99,100]])
print('last element on 2nd row: ', ar[1, 4])

7
3rd element of 1st row:  30
last element on 2nd row:  100


In [5]:
#slicing

ar = np.array([1, 2, 3, 4, 5, 6, 7])

print(ar[1:5])

print(ar[4:])

print(ar[:4])

print(ar[-3:-1])

print(ar[1:5:2])

print(ar[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


In [6]:
ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(ar[1, 2:5])


ar = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(ar[0:3, 1])


print(ar[0:1, 2:3])

[ 8  9 10]
[2 7]
[[3]]


In [7]:
#array will not change
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 17

print(arr)
print(x)


#view will change the main array

arr = np.array([10, 20, 30, 40, 50])
x = arr.view()
arr[0] = 25

print(arr)
print(x)

[17  2  3  4  5]
[1 2 3 4 5]
[25 20 30 40 50]
[25 20 30 40 50]


In [11]:
#1D
arr = np.array([11, 22, 33, 44, 55])
print(ar.shape)

#2D
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
print(ar.shape)

#convert 1d to 2d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new = arr.reshape(3,4)
print(new)

#convert 1d to 3d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new = arr.reshape(2, 3, 2)
print(new)

(2, 5)
(2, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
ar = np.array([11, 22, 33])

for x in ar:
  print(x)


ar = np.array([[15, 25, 35], [45, 55, 65]])
for x in ar:
  print(x)


ar = np.array([[10, 20, 30], [40, 50, 60]])
for x in ar:
  for y in x:
    print(y)

11
22
33
[15 25 35]
[45 55 65]
10
20
30
40
50
60


In [17]:
ar1 = np.array([45, 22, 33])
ar2 = np.array([41, 52, 63])
arr = np.concatenate((ar1, ar2))
print(arr)


#printing in new row
arr1 = np.array([[12, 21], [43, 45]])
arr2 = np.array([[50, 61], [97, 18]])
arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[45 22 33 41 52 63]
[[12 21 50 61]
 [43 45 97 18]]


In [22]:
#sorting
ar = np.array([12, 21, 4, 5])
print(np.sort(ar))


ar = np.array(['bus', 'train', 'cycle'])
print(np.sort(ar))


arr = np.array([[32, 42, 43], [55, 10, 11]])
print(np.sort(arr))

[ 4  5 12 21]
['bus' 'cycle' 'train']
[[32 42 43]
 [10 11 55]]
